add_newline = false

[cmd_duration]
disabled = true

[package]
disabled = true

[git_branch]
symbol = ""

[nodejs]
symbol = "n::"

[python]
symbol = "p::"

[ruby]
symbol = "r::"

[rust]
symbol = "rs::"
